"""Update models with correct table names and relationships

Revision ID: 11d38e92dde8
Revises: 8f51c5f6d4c3
Create Date: 2024-08-12 09:59:17.387400

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "11d38e92dde8"
down_revision = "8f51c5f6d4c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
