"""Update Magazine

Revision ID: 3c1b20ee2c75
Revises: fb557d2d3ecd
Create Date: 2024-08-28 06:19:21.409965

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3c1b20ee2c75"
down_revision = "fb557d2d3ecd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "magazines", sa.Column("discount_quarterly", sa.Float(), nullable=True)
    )
    op.add_column(
        "magazines", sa.Column("discount_half_yearly", sa.Float(), nullable=True)
    )
    op.add_column("magazines", sa.Column("discount_annual", sa.Float(), nullable=True))
    op.drop_column("magazines", "discount")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "magazines",
        sa.Column(
            "discount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("magazines", "discount_annual")
    op.drop_column("magazines", "discount_half_yearly")
    op.drop_column("magazines", "discount_quarterly")
    # ### end Alembic commands ###
